### ISSUE TITLE
Just a Tip About libgeos_c.so.1

### ISSUE THREAD

**Issue by HogwartsRico** [greenplum-db/geospatial#14] opened 2018-05-28 09:17 UTC
when i finished installing  postgis ,i start  run the command below:

>psql -d mydatabase -f ${GPHOME}/share/postgresql/contrib/postgis-2.1/postgis.sql  

but it goes wrong:  

`postgis-2.1.so": libgeos_c.so.1: cannot open shared object file: No such file or directory`  

so i run 
>ldd /opt/gpdb/lib/postgresql/postgis-2.1.so

here is the result  

```	
	linux-vdso.so.1 =>  (0x00007ffebadfe000)
	libgeos_c.so.1 => not found
	libproj.so.12 => not found
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fd9ce074000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd9cdcaa000)
	libgeos-3.5.0.so => /usr/local/geos/lib/libgeos-3.5.0.so (0x00007fd9cd8f9000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd9cd577000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd9cd361000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd9cd15d000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007fd9ccdc9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd9ccbaf000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fd9cc98d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd9cc684000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd9ce97d000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007fd9cabcd000)

```

so i copy the two files  manually  

```
sudo cp /usr/local/proj/lib/libproj.so.12   /opt/gpdb/lib
sudo cp /usr/local/geos/lib/libgeos_c.so.1  /opt/gpdb/lib
```

and finally it works  

And i do all this in Ubuntu

**Comment by kaknikhil** [comment] 2018-05-29 18:53
@HogwartsRico  @zwj19991999 
Thank you for reporting the issue. @jingyimei and I were able to reproduce it locally by using a non default install directory for libproj.

The workaround you suggested does work but we would suggest the following
1. Edit `/etc/ld.so.conf` and add all the non default library paths that are used by geospatial
1. Run `ldconfig`

In our case `/etc/ld.so.conf` looks like this
```
include ld.so.conf.d/*.conf
/build/proj-install/lib
```
We will include these instructions in the README as well.

P.S. We were also able to reproduce this error on  [postgis 2.3.0](https://github.com/postgis/postgis/tree/2.3.0).

**Comment by kaknikhil** [comment] 2018-06-14 20:59
Closing this issue. Added instructions in readme see https://github.com/greenplum-db/geospatial/pull/15

**Closed by kaknikhil** 2018-06-14 20:59 UTC
